package com.fwd.domain;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

@Entity
@Table(name = "customer")
public class Customer implements Serializable {

    @Column(name = "datetime", table = "customer", unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date datetime;

   
    @Column(name = "name", table = "customer", unique = false, updatable = true, insertable = true, nullable = false, length = 100, scale = 0, precision = 0)
    @Basic
    private String name;
    
     @Column(name = "email", table = "customer", unique = false, updatable = true, insertable = true, nullable = false, length = 100, scale = 0, precision = 0)
    @Basic
    private String email;
     
    @Column(name = "phone", table = "customer", unique = false, updatable = true, insertable = true, nullable = false, length = 100, scale = 0, precision = 0)
    @Basic
    private String phone;

    @Column(name = "avatar_path", table = "customer", unique = false, updatable = true, insertable = true, nullable = true, length = 65535, scale = 0, precision = 0)
    @Lob
    @Basic
    private String avatarPath;
    
    @Transient
    private boolean avatarPathChanged = false;
    
    @Column(name = "age", table = "customer", unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private int age;

    @Column(name = "id_customer", table = "customer", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idCustomer;

    
    @Column(name = "approval", table = "customer", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private boolean approval;

    public Customer() {

    }

    public Date getDatetime() {
        return this.datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

   
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAvatarPath() {
        return this.avatarPath;
    }

    public void setAvatarPath(String avatarPath) {
        this.avatarPath = avatarPath;
    }

    public int getAge() {
        return this.age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public Long getIdCustomer() {
        return idCustomer;
    }

    public void setIdCustomer(Long idCustomer) {
        this.idCustomer = idCustomer;
    }
   
    
    public boolean isApproval() {
        return this.approval;
    }

    public void setApproval(boolean approval) {
        this.approval = approval;
    }

    

    public boolean isAvatarPathChanged() {
        return avatarPathChanged;
    }

    public void setAvatarPathChanged(boolean avatarPathChanged) {
        this.avatarPathChanged = avatarPathChanged;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }
    
    
    
}
