package com.fwd.domain;

//
// This file was generated by the JPA Modeler
//
import java.io.Serializable;
import java.util.Date;

public class Customer implements Serializable {

    private Date datetime;
    private String name;
    private String email;
    private String phone;
    private String avatarPath;
    private int age;
    private Long idCustomer;
    private boolean approval;

    public Customer() {

    }

    public Date getDatetime() {
        return this.datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAvatarPath() {
        return this.avatarPath;
    }

    public void setAvatarPath(String avatarPath) {
        this.avatarPath = avatarPath;
    }

    public int getAge() {
        return this.age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public Long getIdCustomer() {
        return idCustomer;
    }

    public void setIdCustomer(Long idCustomer) {
        this.idCustomer = idCustomer;
    }

    public boolean isApproval() {
        return this.approval;
    }

    public void setApproval(boolean approval) {
        this.approval = approval;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

}
