package com.fwd.domain;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.Date;

public class Menu implements Serializable {

    public static final String HOME_SLIDER_TYPE = "HOME-SLIDER";
    public static final String FIRST_MENU_TYPE = "FIRST-MENU";
    
    private String buttonText;
    private String imagePath;
    private String description;
    private boolean active;
    private Long idMenu;
    private Date startTime;
    private String shortDescription;
    private Date endTime;
    private String type;
    private String title;
    private String url;
    private int orders;
    private boolean dataHref;
    
    public Menu() {

    }

    public String getButtonText() {
        return this.buttonText;
    }

    public void setButtonText(String buttonText) {
        this.buttonText = buttonText;
    }

    public String getImagePath() {
        return this.imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public Long getIdMenu() {
        return this.idMenu;
    }

    public void setIdMenu(Long idMenu) {
        this.idMenu = idMenu;
    }

    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public String getShortDescription() {
        return this.shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public int getOrders() {
        return this.orders;
    }

    public void setOrders(int orders) {
        this.orders = orders;
    }
    
    public boolean isDataHref() {
        return this.dataHref;
    }

    public void setDataHref(boolean dataHref) {
        this.dataHref = dataHref;
    }
}
